# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/getor/Dokumenty/C++/AmIHot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/getor/Dokumenty/C++/AmIHot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/getor/Dokumenty/C++/AmIHot/CMakeFiles /home/getor/Dokumenty/C++/AmIHot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/getor/Dokumenty/C++/AmIHot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Amihot

# Build rule for target.
Amihot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Amihot
.PHONY : Amihot

# fast build rule for target.
Amihot/fast:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/build
.PHONY : Amihot/fast

ChipGetter.o: ChipGetter.cpp.o

.PHONY : ChipGetter.o

# target to build an object file
ChipGetter.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/ChipGetter.cpp.o
.PHONY : ChipGetter.cpp.o

ChipGetter.i: ChipGetter.cpp.i

.PHONY : ChipGetter.i

# target to preprocess a source file
ChipGetter.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/ChipGetter.cpp.i
.PHONY : ChipGetter.cpp.i

ChipGetter.s: ChipGetter.cpp.s

.PHONY : ChipGetter.s

# target to generate assembly for a file
ChipGetter.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/ChipGetter.cpp.s
.PHONY : ChipGetter.cpp.s

ChipWindow.o: ChipWindow.cpp.o

.PHONY : ChipWindow.o

# target to build an object file
ChipWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/ChipWindow.cpp.o
.PHONY : ChipWindow.cpp.o

ChipWindow.i: ChipWindow.cpp.i

.PHONY : ChipWindow.i

# target to preprocess a source file
ChipWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/ChipWindow.cpp.i
.PHONY : ChipWindow.cpp.i

ChipWindow.s: ChipWindow.cpp.s

.PHONY : ChipWindow.s

# target to generate assembly for a file
ChipWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/ChipWindow.cpp.s
.PHONY : ChipWindow.cpp.s

Graph.o: Graph.cpp.o

.PHONY : Graph.o

# target to build an object file
Graph.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/Graph.cpp.o
.PHONY : Graph.cpp.o

Graph.i: Graph.cpp.i

.PHONY : Graph.i

# target to preprocess a source file
Graph.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/Graph.cpp.i
.PHONY : Graph.cpp.i

Graph.s: Graph.cpp.s

.PHONY : Graph.s

# target to generate assembly for a file
Graph.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/Graph.cpp.s
.PHONY : Graph.cpp.s

SensorAbstractFeature.o: SensorAbstractFeature.cpp.o

.PHONY : SensorAbstractFeature.o

# target to build an object file
SensorAbstractFeature.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorAbstractFeature.cpp.o
.PHONY : SensorAbstractFeature.cpp.o

SensorAbstractFeature.i: SensorAbstractFeature.cpp.i

.PHONY : SensorAbstractFeature.i

# target to preprocess a source file
SensorAbstractFeature.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorAbstractFeature.cpp.i
.PHONY : SensorAbstractFeature.cpp.i

SensorAbstractFeature.s: SensorAbstractFeature.cpp.s

.PHONY : SensorAbstractFeature.s

# target to generate assembly for a file
SensorAbstractFeature.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorAbstractFeature.cpp.s
.PHONY : SensorAbstractFeature.cpp.s

SensorChip.o: SensorChip.cpp.o

.PHONY : SensorChip.o

# target to build an object file
SensorChip.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorChip.cpp.o
.PHONY : SensorChip.cpp.o

SensorChip.i: SensorChip.cpp.i

.PHONY : SensorChip.i

# target to preprocess a source file
SensorChip.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorChip.cpp.i
.PHONY : SensorChip.cpp.i

SensorChip.s: SensorChip.cpp.s

.PHONY : SensorChip.s

# target to generate assembly for a file
SensorChip.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorChip.cpp.s
.PHONY : SensorChip.cpp.s

SensorFanFeature.o: SensorFanFeature.cpp.o

.PHONY : SensorFanFeature.o

# target to build an object file
SensorFanFeature.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorFanFeature.cpp.o
.PHONY : SensorFanFeature.cpp.o

SensorFanFeature.i: SensorFanFeature.cpp.i

.PHONY : SensorFanFeature.i

# target to preprocess a source file
SensorFanFeature.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorFanFeature.cpp.i
.PHONY : SensorFanFeature.cpp.i

SensorFanFeature.s: SensorFanFeature.cpp.s

.PHONY : SensorFanFeature.s

# target to generate assembly for a file
SensorFanFeature.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorFanFeature.cpp.s
.PHONY : SensorFanFeature.cpp.s

SensorSubfeature.o: SensorSubfeature.cpp.o

.PHONY : SensorSubfeature.o

# target to build an object file
SensorSubfeature.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorSubfeature.cpp.o
.PHONY : SensorSubfeature.cpp.o

SensorSubfeature.i: SensorSubfeature.cpp.i

.PHONY : SensorSubfeature.i

# target to preprocess a source file
SensorSubfeature.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorSubfeature.cpp.i
.PHONY : SensorSubfeature.cpp.i

SensorSubfeature.s: SensorSubfeature.cpp.s

.PHONY : SensorSubfeature.s

# target to generate assembly for a file
SensorSubfeature.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/SensorSubfeature.cpp.s
.PHONY : SensorSubfeature.cpp.s

TempFeature.o: TempFeature.cpp.o

.PHONY : TempFeature.o

# target to build an object file
TempFeature.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/TempFeature.cpp.o
.PHONY : TempFeature.cpp.o

TempFeature.i: TempFeature.cpp.i

.PHONY : TempFeature.i

# target to preprocess a source file
TempFeature.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/TempFeature.cpp.i
.PHONY : TempFeature.cpp.i

TempFeature.s: TempFeature.cpp.s

.PHONY : TempFeature.s

# target to generate assembly for a file
TempFeature.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/TempFeature.cpp.s
.PHONY : TempFeature.cpp.s

TempFeatureWin.o: TempFeatureWin.cpp.o

.PHONY : TempFeatureWin.o

# target to build an object file
TempFeatureWin.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/TempFeatureWin.cpp.o
.PHONY : TempFeatureWin.cpp.o

TempFeatureWin.i: TempFeatureWin.cpp.i

.PHONY : TempFeatureWin.i

# target to preprocess a source file
TempFeatureWin.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/TempFeatureWin.cpp.i
.PHONY : TempFeatureWin.cpp.i

TempFeatureWin.s: TempFeatureWin.cpp.s

.PHONY : TempFeatureWin.s

# target to generate assembly for a file
TempFeatureWin.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/TempFeatureWin.cpp.s
.PHONY : TempFeatureWin.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Amihot.dir/build.make CMakeFiles/Amihot.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Amihot"
	@echo "... edit_cache"
	@echo "... ChipGetter.o"
	@echo "... ChipGetter.i"
	@echo "... ChipGetter.s"
	@echo "... ChipWindow.o"
	@echo "... ChipWindow.i"
	@echo "... ChipWindow.s"
	@echo "... Graph.o"
	@echo "... Graph.i"
	@echo "... Graph.s"
	@echo "... SensorAbstractFeature.o"
	@echo "... SensorAbstractFeature.i"
	@echo "... SensorAbstractFeature.s"
	@echo "... SensorChip.o"
	@echo "... SensorChip.i"
	@echo "... SensorChip.s"
	@echo "... SensorFanFeature.o"
	@echo "... SensorFanFeature.i"
	@echo "... SensorFanFeature.s"
	@echo "... SensorSubfeature.o"
	@echo "... SensorSubfeature.i"
	@echo "... SensorSubfeature.s"
	@echo "... TempFeature.o"
	@echo "... TempFeature.i"
	@echo "... TempFeature.s"
	@echo "... TempFeatureWin.o"
	@echo "... TempFeatureWin.i"
	@echo "... TempFeatureWin.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

